#AUTOGENERATED! DO NOT EDIT! File to edit: dev/14a_callback_data.ipynb (unless otherwise specified).

<<<<<<< HEAD
__all__ = ['CollectDataCallback', 'SamplerCallback']
=======
__all__ = ['CollectDataCallback', 'WeightedDL', 'weighted_databunch']
>>>>>>> master

#Cell
from ..test import *
from ..basics import *

#Cell
class CollectDataCallback(Callback):
<<<<<<< HEAD
    "Collect all batches, along with `pred` and `loss`, into `self.data`"
    def begin_fit(self): self.data = L()
    def after_batch(self): self.data.append(to_detach(to_cpu((self.xb,self.yb,self.pred,self.loss))))

#Cell
class SamplerCallback(Callback):
    "Use weighted sampling in `DataLoader`"
    run_after=TrainEvalCallback
    def __init__(self, dl, cls, **kwargs): store_attr(self, 'dl,cls,kwargs')
    def after_fit(self): self.dl.sampler = self.old_sampler
    def begin_fit(self):
        self.old_sampler = self.dl.sampler
        self.dl.replace_sampler(self.cls, **self.kwargs)

#Cell
@patch
def train_sampler(self:Learner, cls, **kwargs):
    self.add_cb(SamplerCallback(self.dbunch.train_dl, cls, **kwargs))
    return self
=======
    "Collect all batches, along with `pred` and `loss`, into `self.data`. Mainly for testing"
    def begin_fit(self): self.data = L()
    def after_batch(self): self.data.append(to_detach((self.xb,self.yb,self.pred,self.loss)))

#Cell
@delegates()
class WeightedDL(TfmdDL):
    def __init__(self, dataset=None, bs=None, wgts=None, **kwargs):
        super().__init__(dataset=dataset, bs=bs, **kwargs)
        wgts = array([1.]*len(dataset) if wgts is None else wgts)
        self.wgts = wgts/wgts.sum()

    def get_idxs(self):
        if self.n==0: return []
        return list(np.random.choice(self.n, self.n, p=self.wgts))

#Cell
@patch
@delegates(DataSource.databunch)
def weighted_databunch(self:DataSource, wgts, bs=16, **kwargs):
    xtra_kwargs = [{}] * (self.n_subsets-1)
    return dsrc.databunch(bs=bs, dl_type=WeightedDL, dl_kwargs=({'wgts':wgts}, *xtra_kwargs), **kwargs)
>>>>>>> master
